#!/bin/sh

set -o errexit
trap '[ $? -eq 0 ] && exit 0 || echo "Error on line ${LINENO} of ${0}"; exit 1' EXIT

while ! pg_isready -h db -p 5432 -d postgres; do
	echo "waiting for db on postgresql://db:5432/postgres";
	sleep 3;
done

exit 0

DB_CFG_FILE="$(mktemp)"

mkdir -p git
cd /traffic_ops_golang

dlv --accept-multiclient --continue --listen=:6444 --headless --api-version=2 debug -- --cfg="$CFG_FILE" --dbcfg="$DB_CFG_FILE"


while inotifywait --exclude .swp -e modify -r . ;
do
    # find PID of the file generated by `go run .` to kill it. make sure the grep does not match other processes running on the system
    IDS=$(ps ax | grep "/tmp/go-build" | grep "b001/exe/main" | grep -v "grep" | awk '{print $1}')
    if [ ! -z "$IDS" ]
    then
        kill $IDS;
    fi
    go run . &
done;
