#!/bin/sh
#
# Source this file to use PKGS, which is a space delimited list of packges
# to be tested, linted, etc. This avoids running tests on vendored, non Traffic Control packages.
#
# Note the trailing "..." to make the paths recursive.
# See "go help packages" for more info.
#
PKGS="github.com/Comcast/traffic_control/traffic_ops/client/ \
github.com/Comcast/traffic_control/traffic_ops/client/tests/... \
github.com/Comcast/traffic_control/traffic_ops/client/fixtures/..."
