# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# This compose file will expose the ports of each service on the host.
#
#      docker-compose -f docker-compose.yml -f docker-compose.expose-ports.yml up
#

---
version: '3.8'

services:
  db:
    ports:
      - "5432:5432"
  trafficops:
    ports:
      - "6443:443"
  trafficportal:
    ports:
      - "443:443"
  trafficmonitor:
    ports:
      - "80:80"
  trafficrouter:
    ports:
      - "3053:53/tcp"
      - "3053:53/udp"
      - "3080:80"
      - "3443:443"
      - "3333:3333"
      - "2222:3443"
  influxdb:
    ports:
      - "8086:8086"
  edge:
    ports:
      - "9000:80"
  mid-01:
    ports:
      - "9100:80"
  mid-02:
    ports:
      - "9200:80"
  origin:
    ports:
      - "9300:80"
  dns:
    ports:
      - "9353:53/tcp"
      - "9353:53/udp"
  smtp:
    ports:
      - "4443:443"
  static:
    ports:
      - "9443:443"
