#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
FROM golang:1.8
MAINTAINER Dewayne Richardson <dewrich@apache.org>

RUN apt-get -y update
RUN apt-get -y install vim netcat

ARG DIR=github.com/apache/incubator-trafficcontrol
ARG DBHOST
ARG DBPORT
ENV DBHOST=$DBHOST
ENV DBPORT=$DBPORT

#ADD . $DIR
ADD . /go/src/$DIR
ADD lib /go/src/$DIR/lib

WORKDIR /go/src/$DIR/traffic_ops/testing/api

CMD bash -c 'docker/run_api_tests.sh'
 
# vi:syntax=Dockerfile
