---
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
- name: Create Postgres Admin Database User
  postgresql_user:
    encrypted: true
    name: "{{ postgresql_admin_user }}"
    password: "{{ postgresql_admin_user_password }}"
    port: "{{ postgresql_port }}"
    login_host: 127.0.0.1
    role_attr_flags: SUPERUSER,LOGIN,CREATEROLE,CREATEDB,BYPASSRLS
    ssl_rootcert: "{{ postgresql_certs_ca }}"
  no_log: true
  notify: Restart Traffic OpsDB

- name: Create Traffic Ops Database User
  postgresql_user:
    encrypted: true
    name: "{{ todb_username }}"
    password: "{{ todb_password }}"
    port: "{{ postgresql_port }}"
    login_host: 127.0.0.1
    role_attr_flags: SUPERUSER,LOGIN,CREATEDB
    ssl_rootcert: "{{ postgresql_certs_ca }}"
  no_log: true
  notify: Restart Traffic OpsDB

- name: Create Traffic Vault Database User
  postgresql_user:
    encrypted: true
    name: "{{ tvdb_username }}"
    password: "{{ tvdb_password }}"
    port: "{{ postgresql_port }}"
    login_host: 127.0.0.1
    role_attr_flags: LOGIN
    ssl_rootcert: "{{ postgresql_certs_ca }}"
  no_log: true
  notify: Restart Traffic OpsDB

- name: Create Traffic Ops Database
  postgresql_db:
    login_host: 127.0.0.1
    name: "{{ todb_db_name }}"
    owner: "{{ todb_username }}"
    port: "{{ postgresql_port }}"
  notify: Restart Traffic OpsDB

- name: Create Traffic Vault Database
  postgresql_db:
    login_host: 127.0.0.1
    name: "{{ tvdb_db_name }}"
    owner: "{{ tvdb_username }}"
    port: "{{ postgresql_port }}"
  notify: Restart Traffic OpsDB
