#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
FROM dimitri/pgloader:latest
MAINTAINER Dan Kirkwood <dangogh@apache.org>

# Traffic Ops Access
ENV TO_SERVER=$TO_SERVER
ENV TO_USER=$TO_USER
ENV TO_PASSWORD=$TO_PASSWORD

# Mysql Access
ENV MYSQL_HOST=$MYSQL_HOST
ENV MYSQL_PORT=$MYSQL_PORT
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MYSQL_DATABASE=$MYSQL_DATABASE

# Postgres Access
ENV POSTGRES_HOST=$POSTGRES_HOST
ENV POSTGRES_PORT=$POSTGRES_PORT
ENV POSTGRES_DATABASE=$POSTGRES_DATABASE
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# install the tools for getting data
RUN apt-get -y update && apt-get -y install curl mysql-client

ADD mysql-to-postgres.sh .
CMD ./mysql-to-postgres.sh
