/*
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

package ip_allow_test

import (
	"fmt"
	"testing"

	"github.com/apache/trafficcontrol/traffic_ops/testing/api/v1/config"
	"github.com/apache/trafficcontrol/traffic_ops/testing/api/v1/config/ip_allow"
)

var negativeTests = []config.NegativeTest{
	{
		Description: "too few assignments",
		Config:      "foo1=foo",
		Expected:    config.NotEnoughAssignments,
	},
	{
		Description: "empty assignment",
		Config:      "src_ip= foo1=foo",
		Expected:    config.BadAssignmentMatch,
	},
	{
		Description: "missing equals in assignment",
		Config:      "src_ip foo1=foo",
		Expected:    config.BadAssignmentMatch,
	},
	{
		Description: "missing src_ip label",
		Config:      "action=ip_allow method=ALL",
		Expected:    config.MissingLabel,
	},
	{
		Description: "missing action label",
		Config:      "src_ip=0/0 method=ALL",
		Expected:    config.MissingLabel,
	},
	{
		Description: "unknown field",
		Config:      "foo1=foo foo2=foo foo3=foo",
		Expected:    config.InvalidLabel,
	},
	{
		Description: "extra action",
		Config:      "src_ip=0/0 action=ip_allow action=ip_deny",
		Expected:    config.ExcessLabel,
	},
	{
		Description: "extra ip",
		Config:      "src_ip=0/0 dest_ip=0.0.0.0 action=ip_allow",
		Expected:    config.ExcessLabel,
	},
	{
		Description: "invalid label on second line",
		Config: fmt.Sprintf("%s\n\n%s",
			"src_ip=0/0 action=ip_allow",
			"foo1=foo foo2=foo foo3=foo"),
		Expected: config.InvalidLabel,
	},
	{
		Description: "bad src_ip",
		Config:      "src_ip=x action=ip_allow",
		Expected:    config.InvalidIPRange,
	},
	{
		Description: "bad action",
		Config:      "src_ip=0/0 action=ip_allowed",
		Expected:    config.InvalidAction,
	},
	{
		Description: "unknown method",
		Config:      "src_ip=0/0 action=ip_allow method=x",
		Expected:    config.UnknownMethod,
	},
	{
		Description: "bad method delimiter",
		Config:      "src_ip=0/0 action=ip_allow method=GET|",
		Expected:    config.UnknownMethod,
	},
	{
		Description: "bad method delimiter",
		Config:      "src_ip=0/0 action=ip_allow method=GET,",
		Expected:    config.UnknownMethod,
	},
	{
		Description: "bad ip",
		Config:      "dest_ip=bad_ip foo1=foo",
		Expected:    config.InvalidIPRange,
	},
}

var positiveTests = []config.PositiveTest{
	{
		Description: "IPv4",
		Config:      "src_ip=127.0.0.1 action=ip_allow method=ALL",
	},
	{
		Description: "IPv6 shorthand",
		Config:      "src_ip=::1 action=ip_allow method=ALL",
	},
	{
		Description: "IPv4 dash range",
		Config:      "src_ip=0.0.0.0-255.255.255.255 action=ip_allow",
	},
	{
		Description: "Multiple methods",
		Config:      "src_ip=0.0.0.0-255.255.255.255 action=ip_deny method=PUSH|PURGE|DELETE",
	},
	{
		Description: "Multiple methods",
		Config:      "src_ip=0.0.0.0-255.255.255.255 action=ip_deny method=PUSH method=PURGE method=DELETE",
	},
	{
		Description: "IPv6 dash range",
		Config:      "src_ip=::-ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff action=ip_deny method=PUSH|PURGE|DELETE",
	},
	{
		Description: "IPv4 CIDR",
		Config:      "src_ip=123.45.6.0/24 action=ip_deny",
	},
	{
		Description: "IPv4 CIDR (shorthand)",
		Config:      "src_ip=0/0 action=ip_deny method=PUSH|PURGE|DELETE",
	},
	{
		Description: "IPv6 CIDR",
		Config:      "src_ip=::/0 action=ip_deny method=PUSH|PURGE|DELETE",
	},
	{
		Description: "normal config returned from traffic ops",
		Config: fmt.Sprintf("%s\n%s\n%s\n%s\n%s\n",
			"# DO NOT EDIT - Generated by Traffic Ops on Fri Mar 1 18:30:48 UTC 2019",
			"src_ip=127.0.0.1 action=ip_allow method=ALL",
			"src_ip=::1 action=ip_allow method=ALL",
			"src_ip=0.0.0.0-255.255.255.255 action=ip_deny method=PUSH|PURGE|DELETE",
			"src_ip=::-ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff action=ip_deny method=PUSH|PURGE|DELETE"),
	},
	{
		Description: "odd whitespace",
		Config: fmt.Sprintf("%s\n%s\n%s\n",
			"src_ip=127.0.0.1\taction=ip_allow\tmethod=ALL",
			"src_ip=::1  action=ip_allow  method=ALL",
			"src_ip=0.0.0.0-255.255.255.255 \taction=ip_deny  \t method=PUSH|PURGE|DELETE"),
	},
	{
		Description: "multiline config with empty line",
		Config: fmt.Sprintf("%s\n\n%s",
			"src_ip=0/0 action=ip_allow",
			"src_ip=0/0 action=ip_deny"),
	},
	{
		Description: "many empty lines in config",
		Config: fmt.Sprintf("\n%s\n\n%s",
			"src_ip=0/0 action=ip_deny\n",
			"src_ip=0/0 action=ip_allow method=GET\n"),
	},
}

func TestIPAllowConfig(t *testing.T) {

	// Negative Tests
	for _, test := range negativeTests {
		actual := ip_allow.Parse(test.Config)
		if actual == nil || actual.Code() != test.Expected {
			t.Errorf(`
  config: "%v"
  returned error: "%v"
  error should be related to: %v`, test.Config, actual, test.Description)
		}
	}

	// Positive Tests
	for _, test := range positiveTests {
		actual := ip_allow.Parse(test.Config)
		if actual != nil {
			t.Errorf(`
  config: "%v"
  returned error: "%v"
  error should be nil
  description: %v`, test.Config, actual, test.Description)
		}
	}
}
