# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

############################################################
# Dockerfile for trafficops db
############################################################

ARG POSTGRES_VERSION=13.2
FROM postgres:${POSTGRES_VERSION}
ARG POSTGRES_VERSION=13.2
ENV POSTGRES_VERSION=$POSTGRES_VERSION

ENV POSTGRES_PASSWORD=twelve
ENV POSTGRES_DB=traffic_ops
ENV DB_NAME=traffic_ops
ENV DB_USER=traffic_ops
COPY initdb.d /docker-entrypoint-initdb.d
