# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

############################################################
# Dockerfile to build Traffic Monitor debugging container image
# Based on CentOS
############################################################

ARG CENTOS_VERSION=8
FROM centos:${CENTOS_VERSION} as get-delve
ARG CENTOS_VERSION=8

RUN if [[ "${CENTOS_VERSION%%.*}" -eq 7 ]]; then \
        yum -y install dnf || exit 1; \
    fi

RUN dnf -y install epel-release && \
    dnf -y install golang git && \
    go get -u github.com/go-delve/delve/cmd/dlv

FROM trafficmonitor
COPY --from=get-delve /root/go/bin /usr/bin
