#!/usr/bin/env perl
use Mojo::Base -strict;
use File::Basename 'dirname';
use File::Spec::Functions qw(catdir splitdir);
use Data::Dumper;
use Env;

# Start commands for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('TrafficOps');
