/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership.  The ASF
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

-- delete from role_capability
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='ACME:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='ASN:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='ASN:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='ASN:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='ASN:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='ASYNC-STATUS:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='CACHE-GROUP:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='CACHE-GROUP:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='CACHE-GROUP:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='CACHE-GROUP:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='CDN-LOCK:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='CDN-LOCK:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='CDN-SNAPSHOT:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='CDN-SNAPSHOT:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='CDN:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='CDN:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='CDN:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='CDN:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='COORDINATE:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='COORDINATE:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='COORDINATE:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='COORDINATE:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='DELIVERY-SERVICE-SAFE:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='DELIVERY-SERVICE:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='DELIVERY-SERVICE:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='DELIVERY-SERVICE:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='DELIVERY-SERVICE:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='DIVISION:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='DIVISION:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='DIVISION:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='DIVISION:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='DNS-SEC:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='DS-REQUEST:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='DS-REQUEST:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='DS-SECURITY-KEY:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='DS-SECURITY-KEY:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='DS-SECURITY-KEY:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='DS-SECURITY-KEY:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='ISO:GENERATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='ISO:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='ORIGIN:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='ORIGIN:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='ORIGIN:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='ORIGIN:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='PARAMETER:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='PARAMETER:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='PARAMETER:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='PARAMETER:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='PHYSICAL-LOCATION:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='PHYSICAL-LOCATION:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='PHYSICAL-LOCATION:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='PHYSICAL-LOCATION:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='PROFILE:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='PROFILE:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='PROFILE:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='PROFILE:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='REGION:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='REGION:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='REGION:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='REGION:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='SERVER-CAPABILITY:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='SERVER-CAPABILITY:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='SERVER-CAPABILITY:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='SERVER-CAPABILITY:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='SERVER:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='SERVER:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='SERVER:QUEUE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='SERVER:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='SERVER:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='SERVICE-CATEGORY:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='SERVICE-CATEGORY:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='SERVICE-CATEGORY:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='SERVICE-CATEGORY:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='STATIC-DN:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='STATIC-DN:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='STATIC-DN:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='STATIC-DN:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='STATUS:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='STATUS:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='STATUS:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='STATUS:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='TENANT:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='TENANT:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='TENANT:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='TENANT:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='TOPOLOGY:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='TOPOLOGY:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='TOPOLOGY:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='TOPOLOGY:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='TYPE:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='TYPE:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='TYPE:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='TYPE:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='USER:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='USER:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='USER:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='SERVER-CHECK:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='SERVER-CHECK:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='operations') AND cap_name='SERVER-CHECK:DELETE';

DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='steering') AND cap_name='DELIVERY-SERVICE:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='steering') AND cap_name='CDN:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='steering') AND cap_name='TYPE:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='steering') AND cap_name='STEERING:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='steering') AND cap_name='STEERING:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='steering') AND cap_name='STEERING:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='steering') AND cap_name='STEERING:UPDATE';

DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='ACME:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='ASN:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='ASYNC-STATUS:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='CACHE-GROUP:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='CDN-SNAPSHOT:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='CDN:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='COORDINATE:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='DELIVERY-SERVICE:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='DIVISION:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='DS-REQUEST:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='DS-SECURITY-KEY:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='ISO:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='ORIGIN:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='PARAMETER:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='PHYSICAL-LOCATION:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='PROFILE:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='REGION:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='SERVER-CAPABILITY:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='SERVER:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='SERVICE-CATEGORY:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='STATIC-DN:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='STATUS:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='TENANT:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='TOPOLOGY:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='TYPE:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='USER:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='SERVER-CHECK:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='STEERING:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='LOG:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name='read-only') AND cap_name='STAT:READ';

DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'federation')AND cap_name='FEDERATION:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'federation')AND cap_name='FEDERATION:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'federation')AND cap_name='FEDERATION:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'federation')AND cap_name='FEDERATION:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'federation')AND cap_name='FEDERATION-RESOLVER:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'federation')AND cap_name='FEDERATION-RESOLVER:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'federation')AND cap_name='FEDERATION-RESOLVER:DELETE';

DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='ASN:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='CACHE-GROUP:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='CAPABILITY:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='CDN:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='DS-SECURITY-KEY:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='LOG:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='COORDINATE:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='DELIVERY-SERVICE:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='DIVISION:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='SERVER-CHECK:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='FEDERATION:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='JOB:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='JOB:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='JOB:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='JOB:DELETE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='ORIGIN:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='PARAMETER:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='PHYSICAL-LOCATION:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='PROFILE:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='REGION:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='ROLE:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='SERVER:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='STAT:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='STATUS:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='STATIC-DN:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='STEERING:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='TENANT:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='TYPE:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='USER:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='USER:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='DS-REQUEST:READ';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='DS-REQUEST:CREATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='DS-REQUEST:UPDATE';
DELETE FROM role_capability WHERE role_id=(SELECT id FROM role WHERE name = 'portal') AND cap_name='DS-REQUEST:DELETE';

-- delete from capability
DELETE FROM capability WHERE name='ACME:READ';
DELETE FROM capability WHERE name='ACME:CREATE';
DELETE FROM capability WHERE name='ACME:UPDATE';
DELETE FROM capability WHERE name='ACME:DELETE';
DELETE FROM capability WHERE name='DELIVERY-SERVICE:READ';
DELETE FROM capability WHERE name='DELIVERY-SERVICE:CREATE';
DELETE FROM capability WHERE name='DELIVERY-SERVICE:UPDATE';
DELETE FROM capability WHERE name='DELIVERY-SERVICE:DELETE';
DELETE FROM capability WHERE name='DELIVERY-SERVICE-SAFE:UPDATE';
DELETE FROM capability WHERE name='DS-SECURITY-KEY:READ';
DELETE FROM capability WHERE name='DS-SECURITY-KEY:CREATE';
DELETE FROM capability WHERE name='DS-SECURITY-KEY:UPDATE';
DELETE FROM capability WHERE name='DS-SECURITY-KEY:DELETE';
DELETE FROM capability WHERE name='ASN:READ';
DELETE FROM capability WHERE name='ASN:CREATE';
DELETE FROM capability WHERE name='ASN:UPDATE';
DELETE FROM capability WHERE name='ASN:DELETE';
DELETE FROM capability WHERE name='CACHE-GROUP:READ';
DELETE FROM capability WHERE name='CACHE-GROUP:CREATE';
DELETE FROM capability WHERE name='CACHE-GROUP:UPDATE';
DELETE FROM capability WHERE name='CACHE-GROUP:DELETE';
DELETE FROM capability WHERE name='ASYNC-STATUS:READ';
DELETE FROM capability WHERE name='CDN:READ';
DELETE FROM capability WHERE name='CDN:CREATE';
DELETE FROM capability WHERE name='CDN:UPDATE';
DELETE FROM capability WHERE name='CDN:DELETE';
DELETE FROM capability WHERE name='TYPE:READ';
DELETE FROM capability WHERE name='TYPE:CREATE';
DELETE FROM capability WHERE name='TYPE:UPDATE';
DELETE FROM capability WHERE name='TYPE:DELETE';
DELETE FROM capability WHERE name='SERVER:READ';
DELETE FROM capability WHERE name='SERVER:CREATE';
DELETE FROM capability WHERE name='SERVER:UPDATE';
DELETE FROM capability WHERE name='SERVER:DELETE';
DELETE FROM capability WHERE name='SERVER:QUEUE';
DELETE FROM capability WHERE name='PROFILE:READ';
DELETE FROM capability WHERE name='PROFILE:CREATE';
DELETE FROM capability WHERE name='PROFILE:UPDATE';
DELETE FROM capability WHERE name='PROFILE:DELETE';
DELETE FROM capability WHERE name='CAPABILITY:READ';
DELETE FROM capability WHERE name='CAPABILITY:CREATE';
DELETE FROM capability WHERE name='CAPABILITY:UPDATE';
DELETE FROM capability WHERE name='CAPABILITY:DELETE';
DELETE FROM capability WHERE name='CDN-LOCK:READ';
DELETE FROM capability WHERE name='CDN-LOCK:CREATE';
DELETE FROM capability WHERE name='CDN-LOCK:DELETE-OTHERS';
DELETE FROM capability WHERE name='CDN-LOCK:DELETE';
DELETE FROM capability WHERE name='DNS-SEC:READ';
DELETE FROM capability WHERE name='DNS-SEC:CREATE';
DELETE FROM capability WHERE name='DNS-SEC:UPDATE';
DELETE FROM capability WHERE name='DNS-SEC:DELETE';
DELETE FROM capability WHERE name='PARAMETER:READ';
DELETE FROM capability WHERE name='PARAMETER:CREATE';
DELETE FROM capability WHERE name='PARAMETER:UPDATE';
DELETE FROM capability WHERE name='PARAMETER:DELETE';
DELETE FROM capability WHERE name='MONITOR-CONFIG:READ';
DELETE FROM capability WHERE name='FEDERATION:READ';
DELETE FROM capability WHERE name='FEDERATION:CREATE';
DELETE FROM capability WHERE name='FEDERATION:UPDATE';
DELETE FROM capability WHERE name='FEDERATION:DELETE';
DELETE FROM capability WHERE name='CDN-SNAPSHOT:READ';
DELETE FROM capability WHERE name='CDN-SNAPSHOT:CREATE';
DELETE FROM capability WHERE name='COORDINATE:READ';
DELETE FROM capability WHERE name='COORDINATE:CREATE';
DELETE FROM capability WHERE name='COORDINATE:UPDATE';
DELETE FROM capability WHERE name='COORDINATE:DELETE';
DELETE FROM capability WHERE name='REGION:READ';
DELETE FROM capability WHERE name='REGION:CREATE';
DELETE FROM capability WHERE name='REGION:UPDATE';
DELETE FROM capability WHERE name='REGION:DELETE';
DELETE FROM capability WHERE name='DIVISION:READ';
DELETE FROM capability WHERE name='DIVISION:CREATE';
DELETE FROM capability WHERE name='DIVISION:UPDATE';
DELETE FROM capability WHERE name='DIVISION:DELETE';
DELETE FROM capability WHERE name='PHYSICAL-LOCATION:READ';
DELETE FROM capability WHERE name='PHYSICAL-LOCATION:CREATE';
DELETE FROM capability WHERE name='PHYSICAL-LOCATION:UPDATE';
DELETE FROM capability WHERE name='PHYSICAL-LOCATION:DELETE';
DELETE FROM capability WHERE name='DBDUMP:READ';
DELETE FROM capability WHERE name='DS-REQUEST:READ';
DELETE FROM capability WHERE name='DS-REQUEST:CREATE';
DELETE FROM capability WHERE name='DS-REQUEST:UPDATE';
DELETE FROM capability WHERE name='DS-REQUEST:DELETE';
DELETE FROM capability WHERE name='USER:READ';
DELETE FROM capability WHERE name='USER:CREATE';
DELETE FROM capability WHERE name='USER:UPDATE';
DELETE FROM capability WHERE name='STAT:READ';
DELETE FROM capability WHERE name='FEDERATION-RESOLVER:READ';
DELETE FROM capability WHERE name='FEDERATION-RESOLVER:CREATE';
DELETE FROM capability WHERE name='FEDERATION-RESOLVER:DELETE';
DELETE FROM capability WHERE name='ISO:READ';
DELETE FROM capability WHERE name='ISO:GENERATE';
DELETE FROM capability WHERE name='JOB:READ';
DELETE FROM capability WHERE name='JOB:CREATE';
DELETE FROM capability WHERE name='JOB:UPDATE';
DELETE FROM capability WHERE name='JOB:DELETE';
DELETE FROM capability WHERE name='LOG:READ';
DELETE FROM capability WHERE name='ORIGIN:READ';
DELETE FROM capability WHERE name='ORIGIN:CREATE';
DELETE FROM capability WHERE name='ORIGIN:UPDATE';
DELETE FROM capability WHERE name='ORIGIN:DELETE';
DELETE FROM capability WHERE name='PLUGIN:READ';
DELETE FROM capability WHERE name='ROLE:READ';
DELETE FROM capability WHERE name='ROLE:CREATE';
DELETE FROM capability WHERE name='ROLE:UPDATE';
DELETE FROM capability WHERE name='ROLE:DELETE';
DELETE FROM capability WHERE name='SERVER-CAPABILITY:READ';
DELETE FROM capability WHERE name='SERVER-CAPABILITY:CREATE';
DELETE FROM capability WHERE name='SERVER-CAPABILITY:UPDATE';
DELETE FROM capability WHERE name='SERVER-CAPABILITY:DELETE';
DELETE FROM capability WHERE name='SERVER-CHECK:READ';
DELETE FROM capability WHERE name='SERVER-CHECK:CREATE';
DELETE FROM capability WHERE name='SERVER-CHECK:DELETE';
DELETE FROM capability WHERE name='SERVICE-CATEGORY:READ';
DELETE FROM capability WHERE name='SERVICE-CATEGORY:CREATE';
DELETE FROM capability WHERE name='SERVICE-CATEGORY:UPDATE';
DELETE FROM capability WHERE name='SERVICE-CATEGORY:DELETE';
DELETE FROM capability WHERE name='STATIC-DN:READ';
DELETE FROM capability WHERE name='STATIC-DN:CREATE';
DELETE FROM capability WHERE name='STATIC-DN:UPDATE';
DELETE FROM capability WHERE name='STATIC-DN:DELETE';
DELETE FROM capability WHERE name='STATUS:READ';
DELETE FROM capability WHERE name='STATUS:CREATE';
DELETE FROM capability WHERE name='STATUS:UPDATE';
DELETE FROM capability WHERE name='STATUS:DELETE';
DELETE FROM capability WHERE name='STEERING:READ';
DELETE FROM capability WHERE name='STEERING:CREATE';
DELETE FROM capability WHERE name='STEERING:UPDATE';
DELETE FROM capability WHERE name='STEERING:DELETE';
DELETE FROM capability WHERE name='TENANT:READ';
DELETE FROM capability WHERE name='TENANT:CREATE';
DELETE FROM capability WHERE name='TENANT:UPDATE';
DELETE FROM capability WHERE name='TENANT:DELETE';
DELETE FROM capability WHERE name='TOPOLOGY:READ';
DELETE FROM capability WHERE name='TOPOLOGY:CREATE';
DELETE FROM capability WHERE name='TOPOLOGY:UPDATE';
DELETE FROM capability WHERE name='TOPOLOGY:DELETE';
DELETE FROM capability WHERE name='TRAFFIC-VAULT:READ';
