FROM centos/systemd

RUN yum install -y https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-redhat96-9.6-3.noarch.rpm

RUN yum -y install \
  postgresql96 \
  nmap-ncat \
  cpanminus && \
  yum clean all

ENV POSTGRES_HOME $POSTGRES_HOME
ENV PGPASSWORD $PGPASSWORD 
ENV DB_USERNAME $DB_USERNAME
ENV DB_NAME $DB_NAME
ENV DB_USER_PASS $DB_USER_PASS 
ENV DB_SERVER $DB_SERVER
ENV DB_PORT $DB_PORT

ADD dbInit.sh /
CMD /dbInit.sh
