#!/bin/sh
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

#
# Base pre-commit hook. Place this file in ".git/hooks/pre-commit" to activate.
# All executables in the misc/pre-commit-hooks directory will be run, stopping after first failure.

# Fix for SourceTree, which (unless launched from terminal) does not have correct $PATH.
# Check that go is in $PATH, if not, load the ~/.bash_profile which will hopefully update
# $PATH to the proper value.
command -v go >/dev/null 2>&1
if [ $? -ne 0 ]; then
  source ~/.bash_profile
fi

__DIR__="$(cd "$(dirname "${0}")"; echo $(pwd))"
HOOKS="$__DIR__/../../misc/git/pre-commit-hooks/*"

for hook in $HOOKS
do
  if [[ -x "$hook" ]]
  then
    $hook
    if [ $? != 0 ]; then
      exit 1
    fi
  fi
done

exit 0
