// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_goto2.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	"encoding/json"
	"fmt"
	"github.com/Comcast/traffic_control/traffic_ops/goto2/db"
	_ "github.com/Comcast/traffic_control/traffic_ops/goto2/output_format" // needed for swagger
	null "gopkg.in/guregu/null.v3"
)

type DeliveryserviceRegex struct {
	Deliveryservice int64    `db:"deliveryservice" json:"deliveryservice"`
	Regex           int64    `db:"regex" json:"regex"`
	SetNumber       null.Int `db:"set_number" json:"setNumber"`
}

func handleDeliveryserviceRegex(method string, id int, payload []byte) (interface{}, error) {
	if method == "GET" {
		return getDeliveryserviceRegex(id)
	} else if method == "POST" {
		return postDeliveryserviceRegex(payload)
	} else if method == "PUT" {
		return putDeliveryserviceRegex(id, payload)
	} else if method == "DELETE" {
		return delDeliveryserviceRegex(id)
	}
	return nil, nil
}

func getDeliveryserviceRegex(id int) (interface{}, error) {
	if id >= 0 {
		return getDeliveryserviceRegexById(id)
	} else {
		return getDeliveryserviceRegexs()
	}
}

// @Title getDeliveryserviceRegexById
// @Description retrieves the deliveryservice_regex information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    DeliveryserviceRegex
// @Resource /api/2.0
// @Router /api/2.0/deliveryservice_regex/{id} [get]
func getDeliveryserviceRegexById(id int) (interface{}, error) {
	ret := []DeliveryserviceRegex{}
	arg := DeliveryserviceRegex{Deliveryservice: int64(id)}
	nstmt, err := db.GlobalDB.PrepareNamed(`select * from deliveryservice_regex where deliveryservice=:deliveryservice`)
	err = nstmt.Select(&ret, arg)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	nstmt.Close()
	return ret, nil
}

// @Title getDeliveryserviceRegexs
// @Description retrieves the deliveryservice_regex information for a certain id
// @Accept  application/json
// @Success 200 {array}    DeliveryserviceRegex
// @Resource /api/2.0
// @Router /api/2.0/deliveryservice_regex [get]
func getDeliveryserviceRegexs() (interface{}, error) {
	ret := []DeliveryserviceRegex{}
	queryStr := "select * from deliveryservice_regex"
	err := db.GlobalDB.Select(&ret, queryStr)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return ret, nil
}

// @Title postDeliveryserviceRegex
// @Description enter a new deliveryservice_regex
// @Accept  application/json
// @Param                 Body body     DeliveryserviceRegex   true "DeliveryserviceRegex object that should be added to the table"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/deliveryservice_regex [post]
func postDeliveryserviceRegex(payload []byte) (interface{}, error) {
	var v DeliveryserviceRegex
	err := json.Unmarshal(payload, &v)
	if err != nil {
		fmt.Println(err)
	}
	sqlString := "INSERT INTO deliveryservice_regex("
	sqlString += "deliveryservice"
	sqlString += ",regex"
	sqlString += ",set_number"
	sqlString += ") VALUES ("
	sqlString += ":deliveryservice"
	sqlString += ",:regex"
	sqlString += ",:set_number"
	sqlString += ")"
	result, err := db.GlobalDB.NamedExec(sqlString, v)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}

// @Title putDeliveryserviceRegex
// @Description modify an existing deliveryservice_regexentry
// @Accept  application/json
// @Param   id              path    int     true        "The row id"
// @Param                 Body body     DeliveryserviceRegex   true "DeliveryserviceRegex object that should be added to the table"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/deliveryservice_regex/{id}  [put]
func putDeliveryserviceRegex(id int, payload []byte) (interface{}, error) {
	var v DeliveryserviceRegex
	err := json.Unmarshal(payload, &v)
	v.Deliveryservice = int64(id) // overwrite the id in the payload
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	sqlString := "UPDATE deliveryservice_regex SET "
	sqlString += "deliveryservice = :deliveryservice"
	sqlString += ",regex = :regex"
	sqlString += ",set_number = :set_number"
	sqlString += " WHERE deliveryservice=:deliveryservice"
	result, err := db.GlobalDB.NamedExec(sqlString, v)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}

// @Title delDeliveryserviceRegexById
// @Description deletes deliveryservice_regex information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    DeliveryserviceRegex
// @Resource /api/2.0
// @Router /api/2.0/deliveryservice_regex/{id} [delete]
func delDeliveryserviceRegex(id int) (interface{}, error) {
	arg := DeliveryserviceRegex{Deliveryservice: int64(id)}
	result, err := db.GlobalDB.NamedExec("DELETE FROM deliveryservice_regex WHERE id=:id", arg)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}
