// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_goto2.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	"../db"
	"encoding/json"
	"fmt"
	"gopkg.in/guregu/null.v3"
	"time"
)

type DeliveryserviceRegex struct {
	Deliveryservice int64    `db:"deliveryservice" json:"deliveryservice"`
	Regex           int64    `db:"regex" json:"regex"`
	SetNumber       null.Int `db:"set_number" json:"setNumber"`
}

func handleDeliveryserviceRegex(method string, id int, payload []byte) (interface{}, error) {
	if method == "GET" {
		return getDeliveryserviceRegex(id)
	} else if method == "POST" {
		return postDeliveryserviceRegex(payload)
	} else if method == "PUT" {
		return putDeliveryserviceRegex(id, payload)
	} else if method == "DELETE" {
		return delDeliveryserviceRegex(id)
	}
	return nil, nil
}

func getDeliveryserviceRegex(id int) (interface{}, error) {
	ret := []DeliveryserviceRegex{}
	if id >= 0 {
		err := db.GlobalDB.Select(&ret, "select * from deliveryservice_regex where id=$1", id)
		if err != nil {
			fmt.Println(err)
			return nil, err
		}
	} else {
		queryStr := "select * from deliveryservice_regex"
		err := db.GlobalDB.Select(&ret, queryStr)
		if err != nil {
			fmt.Println(err)
			return nil, err
		}
	}
	return ret, nil
}

func postDeliveryserviceRegex(payload []byte) (interface{}, error) {
	var v Asn
	err := json.Unmarshal(payload, &v)
	if err != nil {
		fmt.Println(err)
	}
	sqlString := "INSERT INTO deliveryservice_regex("
	sqlString += "deliveryservice"
	sqlString += ",regex"
	sqlString += ",set_number"
	sqlString += ") VALUES ("
	sqlString += ":deliveryservice"
	sqlString += ",:regex"
	sqlString += ",:set_number"
	sqlString += ")"
	result, err := db.GlobalDB.NamedExec(sqlString, v)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}

func putDeliveryserviceRegex(id int, payload []byte) (interface{}, error) {
	var v Asn
	err := json.Unmarshal(payload, &v)
	v.Id = int64(id) // overwirte the id in the payload
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	v.LastUpdated = time.Now()
	sqlString := "UPDATE deliveryservice_regex SET "
	sqlString += "deliveryservice = :deliveryservice"
	sqlString += ",regex = :regex"
	sqlString += ",set_number = :set_number"
	sqlString += " WHERE id=:id"
	result, err := db.GlobalDB.NamedExec(sqlString, v)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}

func delDeliveryserviceRegex(id int) (interface{}, error) {
	result, err := db.GlobalDB.Exec("DELETE FROM deliveryservice_regex WHERE id=$1", id)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}
