// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_goto2.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	"../db"
	"encoding/json"
	"fmt"
	"time"
)

type DeliveryserviceTmuser struct {
	Deliveryservice int64     `db:"deliveryservice" json:"deliveryservice"`
	TmUserId        int64     `db:"tm_user_id" json:"tmUserId"`
	LastUpdated     time.Time `db:"last_updated" json:"lastUpdated"`
}

func handleDeliveryserviceTmuser(method string, id int, payload []byte) (interface{}, error) {
	if method == "GET" {
		return getDeliveryserviceTmuser(id)
	} else if method == "POST" {
		return postDeliveryserviceTmuser(payload)
	} else if method == "PUT" {
		return putDeliveryserviceTmuser(id, payload)
	} else if method == "DELETE" {
		return delDeliveryserviceTmuser(id)
	}
	return nil, nil
}

func getDeliveryserviceTmuser(id int) (interface{}, error) {
	ret := []DeliveryserviceTmuser{}
	arg := DeliveryserviceTmuser{Deliveryservice: int64(id)}
	if id >= 0 {
		nstmt, err := db.GlobalDB.PrepareNamed(`select * from deliveryservice_tmuser where deliveryservice=:id`)
		err = nstmt.Select(&ret, arg)
		if err != nil {
			fmt.Println(err)
			return nil, err
		}
		nstmt.Close()
	} else {
		queryStr := "select * from deliveryservice_tmuser"
		err := db.GlobalDB.Select(&ret, queryStr)
		if err != nil {
			fmt.Println(err)
			return nil, err
		}
	}
	return ret, nil
}

func postDeliveryserviceTmuser(payload []byte) (interface{}, error) {
	var v Asn
	err := json.Unmarshal(payload, &v)
	if err != nil {
		fmt.Println(err)
	}
	sqlString := "INSERT INTO deliveryservice_tmuser("
	sqlString += "deliveryservice"
	sqlString += ",tm_user_id"
	sqlString += ") VALUES ("
	sqlString += ":deliveryservice"
	sqlString += ",:tm_user_id"
	sqlString += ")"
	result, err := db.GlobalDB.NamedExec(sqlString, v)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}

func putDeliveryserviceTmuser(id int, payload []byte) (interface{}, error) {
	var v Asn
	err := json.Unmarshal(payload, &v)
	v.Id = int64(id) // overwirte the id in the payload
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	v.LastUpdated = time.Now()
	sqlString := "UPDATE deliveryservice_tmuser SET "
	sqlString += "deliveryservice = :deliveryservice"
	sqlString += ",tm_user_id = :tm_user_id"
	sqlString += ",last_updated = :last_updated"
	sqlString += " WHERE id=:id"
	result, err := db.GlobalDB.NamedExec(sqlString, v)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}

func delDeliveryserviceTmuser(id int) (interface{}, error) {
	arg := DeliveryserviceTmuser{Deliveryservice: int64(id)}
	result, err := db.GlobalDB.NamedExec("DELETE FROM deliveryservice_tmuser WHERE id=:id", arg)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}
