// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_goto2.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	"../db"
	"encoding/json"
	"fmt"
	"time"
)

type FederationDeliveryservice struct {
	Federation      int64     `db:"federation" json:"federation"`
	Deliveryservice int64     `db:"deliveryservice" json:"deliveryservice"`
	LastUpdated     time.Time `db:"last_updated" json:"lastUpdated"`
}

func handleFederationDeliveryservice(method string, id int, payload []byte) (interface{}, error) {
	if method == "GET" {
		return getFederationDeliveryservice(id)
	} else if method == "POST" {
		return postFederationDeliveryservice(payload)
	} else if method == "PUT" {
		return putFederationDeliveryservice(id, payload)
	} else if method == "DELETE" {
		return delFederationDeliveryservice(id)
	}
	return nil, nil
}

func getFederationDeliveryservice(id int) (interface{}, error) {
	ret := []FederationDeliveryservice{}
	if id >= 0 {
		err := db.GlobalDB.Select(&ret, "select * from federation_deliveryservice where id=$1", id)
		if err != nil {
			fmt.Println(err)
			return nil, err
		}
	} else {
		queryStr := "select * from federation_deliveryservice"
		err := db.GlobalDB.Select(&ret, queryStr)
		if err != nil {
			fmt.Println(err)
			return nil, err
		}
	}
	return ret, nil
}

func postFederationDeliveryservice(payload []byte) (interface{}, error) {
	var v Asn
	err := json.Unmarshal(payload, &v)
	if err != nil {
		fmt.Println(err)
	}
	sqlString := "INSERT INTO federation_deliveryservice("
	sqlString += "federation"
	sqlString += ",deliveryservice"
	sqlString += ") VALUES ("
	sqlString += ":federation"
	sqlString += ",:deliveryservice"
	sqlString += ")"
	result, err := db.GlobalDB.NamedExec(sqlString, v)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}

func putFederationDeliveryservice(id int, payload []byte) (interface{}, error) {
	var v Asn
	err := json.Unmarshal(payload, &v)
	v.Id = int64(id) // overwirte the id in the payload
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	v.LastUpdated = time.Now()
	sqlString := "UPDATE federation_deliveryservice SET "
	sqlString += "federation = :federation"
	sqlString += ",deliveryservice = :deliveryservice"
	sqlString += ",last_updated = :last_updated"
	sqlString += " WHERE id=:id"
	result, err := db.GlobalDB.NamedExec(sqlString, v)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}

func delFederationDeliveryservice(id int) (interface{}, error) {
	result, err := db.GlobalDB.Exec("DELETE FROM federation_deliveryservice WHERE id=$1", id)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}
