// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_goto2.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	"encoding/json"
	"fmt"
	"github.com/Comcast/traffic_control/traffic_ops/goto2/db"
	_ "github.com/Comcast/traffic_control/traffic_ops/goto2/output_format" // needed for swagger
	"time"
)

type FederationResolver struct {
	Id          int64     `db:"id" json:"id"`
	IpAddress   string    `db:"ip_address" json:"ipAddress"`
	Type        int64     `db:"type" json:"type"`
	LastUpdated time.Time `db:"last_updated" json:"lastUpdated"`
}

func handleFederationResolver(method string, id int, payload []byte) (interface{}, error) {
	if method == "GET" {
		return getFederationResolver(id)
	} else if method == "POST" {
		return postFederationResolver(payload)
	} else if method == "PUT" {
		return putFederationResolver(id, payload)
	} else if method == "DELETE" {
		return delFederationResolver(id)
	}
	return nil, nil
}

func getFederationResolver(id int) (interface{}, error) {
	if id >= 0 {
		return getFederationResolverById(id)
	} else {
		return getFederationResolvers()
	}
}

// @Title getFederationResolverById
// @Description retrieves the federation_resolver information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    FederationResolver
// @Resource /api/2.0
// @Router /api/2.0/federation_resolver/{id} [get]
func getFederationResolverById(id int) (interface{}, error) {
	ret := []FederationResolver{}
	arg := FederationResolver{Id: int64(id)}
	nstmt, err := db.GlobalDB.PrepareNamed(`select * from federation_resolver where id=:id`)
	err = nstmt.Select(&ret, arg)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	nstmt.Close()
	return ret, nil
}

// @Title getFederationResolvers
// @Description retrieves the federation_resolver information for a certain id
// @Accept  application/json
// @Success 200 {array}    FederationResolver
// @Resource /api/2.0
// @Router /api/2.0/federation_resolver [get]
func getFederationResolvers() (interface{}, error) {
	ret := []FederationResolver{}
	queryStr := "select * from federation_resolver"
	err := db.GlobalDB.Select(&ret, queryStr)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return ret, nil
}

// @Title postFederationResolver
// @Description enter a new federation_resolver
// @Accept  application/json
// @Param            IpAddress json     string   false "ip_address description"
// @Param                 Type json      int64   false "type description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/federation_resolver [post]
func postFederationResolver(payload []byte) (interface{}, error) {
	var v FederationResolver
	err := json.Unmarshal(payload, &v)
	if err != nil {
		fmt.Println(err)
	}
	sqlString := "INSERT INTO federation_resolver("
	sqlString += "ip_address"
	sqlString += ",type"
	sqlString += ") VALUES ("
	sqlString += ":ip_address"
	sqlString += ",:type"
	sqlString += ")"
	result, err := db.GlobalDB.NamedExec(sqlString, v)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}

// @Title putFederationResolver
// @Description modify an existing federation_resolverentry
// @Accept  application/json
// @Param            IpAddress json     string   false "ip_address description"
// @Param                 Type json      int64   false "type description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/federation_resolver [put]
func putFederationResolver(id int, payload []byte) (interface{}, error) {
	var v FederationResolver
	err := json.Unmarshal(payload, &v)
	v.Id = int64(id) // overwrite the id in the payload
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	v.LastUpdated = time.Now()
	sqlString := "UPDATE federation_resolver SET "
	sqlString += "ip_address = :ip_address"
	sqlString += ",type = :type"
	sqlString += ",last_updated = :last_updated"
	sqlString += " WHERE id=:id"
	result, err := db.GlobalDB.NamedExec(sqlString, v)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}

// @Title delFederationResolverById
// @Description deletes federation_resolver information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    FederationResolver
// @Resource /api/2.0
// @Router /api/2.0/federation_resolver/{id} [delete]
func delFederationResolver(id int) (interface{}, error) {
	arg := FederationResolver{Id: int64(id)}
	result, err := db.GlobalDB.NamedExec("DELETE FROM federation_resolver WHERE id=:id", arg)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}
