// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_goto2.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	"encoding/json"
	"fmt"
	"github.com/Comcast/traffic_control/traffic_ops/goto2/db"
	_ "github.com/Comcast/traffic_control/traffic_ops/goto2/output_format" // needed for swagger
	null "gopkg.in/guregu/null.v3"
	"time"
)

type Federation struct {
	Id          int64       `db:"id" json:"id"`
	Cname       string      `db:"cname" json:"cname"`
	Description null.String `db:"description" json:"description"`
	Ttl         int64       `db:"ttl" json:"ttl"`
	LastUpdated time.Time   `db:"last_updated" json:"lastUpdated"`
}

func handleFederation(method string, id int, payload []byte) (interface{}, error) {
	if method == "GET" {
		return getFederation(id)
	} else if method == "POST" {
		return postFederation(payload)
	} else if method == "PUT" {
		return putFederation(id, payload)
	} else if method == "DELETE" {
		return delFederation(id)
	}
	return nil, nil
}

func getFederation(id int) (interface{}, error) {
	if id >= 0 {
		return getFederationById(id)
	} else {
		return getFederations()
	}
}

// @Title getFederationById
// @Description retrieves the federation information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    Federation
// @Resource /api/2.0
// @Router /api/2.0/federation/{id} [get]
func getFederationById(id int) (interface{}, error) {
	ret := []Federation{}
	arg := Federation{Id: int64(id)}
	nstmt, err := db.GlobalDB.PrepareNamed(`select * from federation where id=:id`)
	err = nstmt.Select(&ret, arg)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	nstmt.Close()
	return ret, nil
}

// @Title getFederations
// @Description retrieves the federation information for a certain id
// @Accept  application/json
// @Success 200 {array}    Federation
// @Resource /api/2.0
// @Router /api/2.0/federation [get]
func getFederations() (interface{}, error) {
	ret := []Federation{}
	queryStr := "select * from federation"
	err := db.GlobalDB.Select(&ret, queryStr)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return ret, nil
}

// @Title postFederation
// @Description enter a new federation
// @Accept  application/json
// @Param                 Body body     Federation   true "Federation object that should be added to the table"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/federation [post]
func postFederation(payload []byte) (interface{}, error) {
	var v Federation
	err := json.Unmarshal(payload, &v)
	if err != nil {
		fmt.Println(err)
	}
	sqlString := "INSERT INTO federation("
	sqlString += "cname"
	sqlString += ",description"
	sqlString += ",ttl"
	sqlString += ") VALUES ("
	sqlString += ":cname"
	sqlString += ",:description"
	sqlString += ",:ttl"
	sqlString += ")"
	result, err := db.GlobalDB.NamedExec(sqlString, v)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}

// @Title putFederation
// @Description modify an existing federationentry
// @Accept  application/json
// @Param                 Body body     Federation   true "Federation object that should be added to the table"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/federation [put]
func putFederation(id int, payload []byte) (interface{}, error) {
	var v Federation
	err := json.Unmarshal(payload, &v)
	v.Id = int64(id) // overwrite the id in the payload
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	v.LastUpdated = time.Now()
	sqlString := "UPDATE federation SET "
	sqlString += "cname = :cname"
	sqlString += ",description = :description"
	sqlString += ",ttl = :ttl"
	sqlString += ",last_updated = :last_updated"
	sqlString += " WHERE id=:id"
	result, err := db.GlobalDB.NamedExec(sqlString, v)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}

// @Title delFederationById
// @Description deletes federation information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    Federation
// @Resource /api/2.0
// @Router /api/2.0/federation/{id} [delete]
func delFederation(id int) (interface{}, error) {
	arg := Federation{Id: int64(id)}
	result, err := db.GlobalDB.NamedExec("DELETE FROM federation WHERE id=:id", arg)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}
