// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_to_start.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	"encoding/json"
	_ "github.com/Comcast/traffic_control/traffic_ops/experimental/server/output_format" // needed for swagger
	"github.com/jmoiron/sqlx"
	null "gopkg.in/guregu/null.v3"
	"log"
	"time"
)

type JobStatus struct {
	Id          int64          `db:"id" json:"id"`
	Name        null.String    `db:"name" json:"name"`
	Description null.String    `db:"description" json:"description"`
	LastUpdated time.Time      `db:"last_updated" json:"lastUpdated"`
	Links       JobStatusLinks `json:"_links" db:-`
}

type JobStatusLinks struct {
	Self string `db:"self" json:"_self"`
}

type JobStatusLink struct {
	ID  int64  `db:"job_status" json:"id"`
	Ref string `db:"job_status_id_ref" json:"_ref"`
}

// @Title getJobStatusById
// @Description retrieves the job_status information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    JobStatus
// @Resource /api/2.0
// @Router /api/2.0/job_status/{id} [get]
func getJobStatusById(id int, db *sqlx.DB) (interface{}, error) {
	ret := []JobStatus{}
	arg := JobStatus{}
	arg.Id = int64(id)
	queryStr := "select *, concat('" + API_PATH + "job_status/', id) as self "
	queryStr += " from job_status where id=:id"
	nstmt, err := db.PrepareNamed(queryStr)
	err = nstmt.Select(&ret, arg)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	nstmt.Close()
	return ret, nil
}

// @Title getJobStatuss
// @Description retrieves the job_status
// @Accept  application/json
// @Success 200 {array}    JobStatus
// @Resource /api/2.0
// @Router /api/2.0/job_status [get]
func getJobStatuss(db *sqlx.DB) (interface{}, error) {
	ret := []JobStatus{}
	queryStr := "select *, concat('" + API_PATH + "job_status/', id) as self "
	queryStr += " from job_status"
	err := db.Select(&ret, queryStr)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	return ret, nil
}

// @Title postJobStatus
// @Description enter a new job_status
// @Accept  application/json
// @Param                 Body body     JobStatus   true "JobStatus object that should be added to the table"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/job_status [post]
func postJobStatus(payload []byte, db *sqlx.DB) (interface{}, error) {
	var v JobStatus
	err := json.Unmarshal(payload, &v)
	if err != nil {
		log.Println(err)
	}
	sqlString := "INSERT INTO job_status("
	sqlString += "name"
	sqlString += ",description"
	sqlString += ") VALUES ("
	sqlString += ":name"
	sqlString += ",:description"
	sqlString += ")"
	result, err := db.NamedExec(sqlString, v)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	return result, err
}

// @Title putJobStatus
// @Description modify an existing job_statusentry
// @Accept  application/json
// @Param   id              path    int     true        "The row id"
// @Param                 Body body     JobStatus   true "JobStatus object that should be added to the table"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/job_status/{id}  [put]
func putJobStatus(id int, payload []byte, db *sqlx.DB) (interface{}, error) {
	var v JobStatus
	err := json.Unmarshal(payload, &v)
	v.Id = int64(id) // overwrite the id in the payload
	if err != nil {
		log.Println(err)
		return nil, err
	}
	v.LastUpdated = time.Now()
	sqlString := "UPDATE job_status SET "
	sqlString += "name = :name"
	sqlString += ",description = :description"
	sqlString += ",last_updated = :last_updated"
	sqlString += " WHERE id=:id"
	result, err := db.NamedExec(sqlString, v)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	return result, err
}

// @Title delJobStatusById
// @Description deletes job_status information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    JobStatus
// @Resource /api/2.0
// @Router /api/2.0/job_status/{id} [delete]
func delJobStatus(id int, db *sqlx.DB) (interface{}, error) {
	arg := JobStatus{}
	arg.Id = int64(id)
	result, err := db.NamedExec("DELETE FROM job_status WHERE id=:id", arg)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	return result, err
}
