// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_goto2.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	"encoding/json"
	_ "github.com/Comcast/traffic_control/traffic_ops/goto2/output_format" // needed for swagger
	"github.com/jmoiron/sqlx"
	"log"
	"time"
)

type ProfileParameter struct {
	Profile     int64     `db:"profile" json:"profile"`
	Parameter   int64     `db:"parameter" json:"parameter"`
	LastUpdated time.Time `db:"last_updated" json:"lastUpdated"`
}

// @Title getProfileParameterById
// @Description retrieves the profile_parameter information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    ProfileParameter
// @Resource /api/2.0
// @Router /api/2.0/profile_parameter/{id} [get]
func getProfileParameterById(id int, db *sqlx.DB) (interface{}, error) {
	ret := []ProfileParameter{}
	arg := ProfileParameter{Profile: int64(id)}
	nstmt, err := db.PrepareNamed(`select * from profile_parameter where profile=:profile`)
	err = nstmt.Select(&ret, arg)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	nstmt.Close()
	return ret, nil
}

// @Title getProfileParameters
// @Description retrieves the profile_parameter information for a certain id
// @Accept  application/json
// @Success 200 {array}    ProfileParameter
// @Resource /api/2.0
// @Router /api/2.0/profile_parameter [get]
func getProfileParameters(db *sqlx.DB) (interface{}, error) {
	ret := []ProfileParameter{}
	queryStr := "select * from profile_parameter"
	err := db.Select(&ret, queryStr)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	return ret, nil
}

// @Title postProfileParameter
// @Description enter a new profile_parameter
// @Accept  application/json
// @Param                 Body body     ProfileParameter   true "ProfileParameter object that should be added to the table"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/profile_parameter [post]
func postProfileParameter(payload []byte, db *sqlx.DB) (interface{}, error) {
	var v ProfileParameter
	err := json.Unmarshal(payload, &v)
	if err != nil {
		log.Println(err)
	}
	sqlString := "INSERT INTO profile_parameter("
	sqlString += "profile"
	sqlString += ",parameter"
	sqlString += ") VALUES ("
	sqlString += ":profile"
	sqlString += ",:parameter"
	sqlString += ")"
	result, err := db.NamedExec(sqlString, v)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	return result, err
}

// @Title putProfileParameter
// @Description modify an existing profile_parameterentry
// @Accept  application/json
// @Param   id              path    int     true        "The row id"
// @Param                 Body body     ProfileParameter   true "ProfileParameter object that should be added to the table"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/profile_parameter/{id}  [put]
func putProfileParameter(id int, payload []byte, db *sqlx.DB) (interface{}, error) {
	var v ProfileParameter
	err := json.Unmarshal(payload, &v)
	v.Profile = int64(id) // overwrite the id in the payload
	if err != nil {
		log.Println(err)
		return nil, err
	}
	v.LastUpdated = time.Now()
	sqlString := "UPDATE profile_parameter SET "
	sqlString += "profile = :profile"
	sqlString += ",parameter = :parameter"
	sqlString += ",last_updated = :last_updated"
	sqlString += " WHERE profile=:profile"
	result, err := db.NamedExec(sqlString, v)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	return result, err
}

// @Title delProfileParameterById
// @Description deletes profile_parameter information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    ProfileParameter
// @Resource /api/2.0
// @Router /api/2.0/profile_parameter/{id} [delete]
func delProfileParameter(id int, db *sqlx.DB) (interface{}, error) {
	arg := ProfileParameter{Profile: int64(id)}
	result, err := db.NamedExec("DELETE FROM profile_parameter WHERE id=:id", arg)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	return result, err
}
