// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_goto2.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	"encoding/json"
	"fmt"
	"github.com/Comcast/traffic_control/traffic_ops/goto2/db"
	_ "github.com/Comcast/traffic_control/traffic_ops/goto2/output_format" // needed for swagger
	null "gopkg.in/guregu/null.v3"
)

type Role struct {
	Id          int64       `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description null.String `db:"description" json:"description"`
	PrivLevel   int64       `db:"priv_level" json:"privLevel"`
}

func handleRole(method string, id int, payload []byte) (interface{}, error) {
	if method == "GET" {
		return getRole(id)
	} else if method == "POST" {
		return postRole(payload)
	} else if method == "PUT" {
		return putRole(id, payload)
	} else if method == "DELETE" {
		return delRole(id)
	}
	return nil, nil
}

func getRole(id int) (interface{}, error) {
	if id >= 0 {
		return getRoleById(id)
	} else {
		return getRoles()
	}
}

// @Title getRoleById
// @Description retrieves the role information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    Role
// @Resource /api/2.0
// @Router /api/2.0/role/{id} [get]
func getRoleById(id int) (interface{}, error) {
	ret := []Role{}
	arg := Role{Id: int64(id)}
	nstmt, err := db.GlobalDB.PrepareNamed(`select * from role where id=:id`)
	err = nstmt.Select(&ret, arg)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	nstmt.Close()
	return ret, nil
}

// @Title getRoles
// @Description retrieves the role information for a certain id
// @Accept  application/json
// @Success 200 {array}    Role
// @Resource /api/2.0
// @Router /api/2.0/role [get]
func getRoles() (interface{}, error) {
	ret := []Role{}
	queryStr := "select * from role"
	err := db.GlobalDB.Select(&ret, queryStr)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return ret, nil
}

// @Title postRole
// @Description enter a new role
// @Accept  application/json
// @Param                 Body body     Role   true "Role object that should be added to the table"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/role [post]
func postRole(payload []byte) (interface{}, error) {
	var v Role
	err := json.Unmarshal(payload, &v)
	if err != nil {
		fmt.Println(err)
	}
	sqlString := "INSERT INTO role("
	sqlString += "name"
	sqlString += ",description"
	sqlString += ",priv_level"
	sqlString += ") VALUES ("
	sqlString += ":name"
	sqlString += ",:description"
	sqlString += ",:priv_level"
	sqlString += ")"
	result, err := db.GlobalDB.NamedExec(sqlString, v)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}

// @Title putRole
// @Description modify an existing roleentry
// @Accept  application/json
// @Param                 Body body     Role   true "Role object that should be added to the table"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/role [put]
func putRole(id int, payload []byte) (interface{}, error) {
	var v Role
	err := json.Unmarshal(payload, &v)
	v.Id = int64(id) // overwrite the id in the payload
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	sqlString := "UPDATE role SET "
	sqlString += "name = :name"
	sqlString += ",description = :description"
	sqlString += ",priv_level = :priv_level"
	sqlString += " WHERE id=:id"
	result, err := db.GlobalDB.NamedExec(sqlString, v)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}

// @Title delRoleById
// @Description deletes role information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    Role
// @Resource /api/2.0
// @Router /api/2.0/role/{id} [delete]
func delRole(id int) (interface{}, error) {
	arg := Role{Id: int64(id)}
	result, err := db.GlobalDB.NamedExec("DELETE FROM role WHERE id=:id", arg)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}
