// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_goto2.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	"encoding/json"
	"fmt"
	"github.com/Comcast/traffic_control/traffic_ops/goto2/db"
	"time"
)

type StatsSummary struct {
	Id                  int64     `db:"id" json:"id"`
	CdnName             string    `db:"cdn_name" json:"cdnName"`
	DeliveryserviceName string    `db:"deliveryservice_name" json:"deliveryserviceName"`
	StatName            string    `db:"stat_name" json:"statName"`
	StatValue           float64   `db:"stat_value" json:"statValue"`
	SummaryTime         time.Time `db:"summary_time" json:"summaryTime"`
	StatDate            time.Time `db:"stat_date" json:"statDate"`
}

func handleStatsSummary(method string, id int, payload []byte) (interface{}, error) {
	if method == "GET" {
		return getStatsSummary(id)
	} else if method == "POST" {
		return postStatsSummary(payload)
	} else if method == "PUT" {
		return putStatsSummary(id, payload)
	} else if method == "DELETE" {
		return delStatsSummary(id)
	}
	return nil, nil
}

func getStatsSummary(id int) (interface{}, error) {
	ret := []StatsSummary{}
	arg := StatsSummary{Id: int64(id)}
	if id >= 0 {
		nstmt, err := db.GlobalDB.PrepareNamed(`select * from stats_summary where id=:id`)
		err = nstmt.Select(&ret, arg)
		if err != nil {
			fmt.Println(err)
			return nil, err
		}
		nstmt.Close()
	} else {
		queryStr := "select * from stats_summary"
		err := db.GlobalDB.Select(&ret, queryStr)
		if err != nil {
			fmt.Println(err)
			return nil, err
		}
	}
	return ret, nil
}

func postStatsSummary(payload []byte) (interface{}, error) {
	var v StatsSummary
	err := json.Unmarshal(payload, &v)
	if err != nil {
		fmt.Println(err)
	}
	sqlString := "INSERT INTO stats_summary("
	sqlString += "cdn_name"
	sqlString += ",deliveryservice_name"
	sqlString += ",stat_name"
	sqlString += ",stat_value"
	sqlString += ",summary_time"
	sqlString += ",stat_date"
	sqlString += ") VALUES ("
	sqlString += ":cdn_name"
	sqlString += ",:deliveryservice_name"
	sqlString += ",:stat_name"
	sqlString += ",:stat_value"
	sqlString += ",:summary_time"
	sqlString += ",:stat_date"
	sqlString += ")"
	result, err := db.GlobalDB.NamedExec(sqlString, v)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}

func putStatsSummary(id int, payload []byte) (interface{}, error) {
	var v StatsSummary
	err := json.Unmarshal(payload, &v)
	v.Id = int64(id) // overwrite the id in the payload
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	sqlString := "UPDATE stats_summary SET "
	sqlString += "cdn_name = :cdn_name"
	sqlString += ",deliveryservice_name = :deliveryservice_name"
	sqlString += ",stat_name = :stat_name"
	sqlString += ",stat_value = :stat_value"
	sqlString += ",summary_time = :summary_time"
	sqlString += ",stat_date = :stat_date"
	sqlString += " WHERE id=:id"
	result, err := db.GlobalDB.NamedExec(sqlString, v)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}

func delStatsSummary(id int) (interface{}, error) {
	arg := StatsSummary{Id: int64(id)}
	result, err := db.GlobalDB.NamedExec("DELETE FROM stats_summary WHERE id=:id", arg)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}
