// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by get_structs.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	"errors"
	"fmt"
	"github.com/Comcast/traffic_control/traffic_ops/goto2/db"
	"gopkg.in/guregu/null.v3"
)

// This is not in the tm_user.go file because that gets (re) generated still

func GetTmUserByName(username string) (TmUser, error) {

	ret := []TmUser{}
	// this works in pq - $1
	// err := db.GlobalDB.Get(&ret, "select * from tm_user where username=$1", username)
	// if err != nil {
	// 	fmt.Println(err)
	// }

	// this works in mysql - ?
	// err := db.GlobalDB.Get(&ret, "select * from tm_user where username=?", username)
	// if err != nil {
	// 	fmt.Println(err)
	// }

	// this works in both
	arg := TmUser{Username: null.StringFrom(username)}
	nstmt, err := db.GlobalDB.PrepareNamed(`select * from tm_user where username=:username`)
	err = nstmt.Select(&ret, arg)
	if err != nil {
		fmt.Println(err)
	}
	if len(ret) != 1 {
		err = errors.New("Username " + username + " is not unique!")
	}
	nstmt.Close()
	return ret[0], err
}
