// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_goto2.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	"encoding/json"
	"fmt"
	"github.com/Comcast/traffic_control/traffic_ops/goto2/db"
	_ "github.com/Comcast/traffic_control/traffic_ops/goto2/output_format" // needed for swagger
	null "gopkg.in/guregu/null.v3"
	"time"
)

type ToExtension struct {
	Id                    int64       `db:"id" json:"id"`
	Name                  string      `db:"name" json:"name"`
	Version               string      `db:"version" json:"version"`
	InfoUrl               string      `db:"info_url" json:"infoUrl"`
	ScriptFile            string      `db:"script_file" json:"scriptFile"`
	Isactive              int64       `db:"isactive" json:"isactive"`
	AdditionalConfigJson  null.String `db:"additional_config_json" json:"additionalConfigJson"`
	Description           null.String `db:"description" json:"description"`
	ServercheckShortName  null.String `db:"servercheck_short_name" json:"servercheckShortName"`
	ServercheckColumnName null.String `db:"servercheck_column_name" json:"servercheckColumnName"`
	Type                  int64       `db:"type" json:"type"`
	LastUpdated           time.Time   `db:"last_updated" json:"lastUpdated"`
}

func handleToExtension(method string, id int, payload []byte) (interface{}, error) {
	if method == "GET" {
		return getToExtension(id)
	} else if method == "POST" {
		return postToExtension(payload)
	} else if method == "PUT" {
		return putToExtension(id, payload)
	} else if method == "DELETE" {
		return delToExtension(id)
	}
	return nil, nil
}

func getToExtension(id int) (interface{}, error) {
	if id >= 0 {
		return getToExtensionById(id)
	} else {
		return getToExtensions()
	}
}

// @Title getToExtensionById
// @Description retrieves the to_extension information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    ToExtension
// @Resource /api/2.0
// @Router /api/2.0/to_extension/{id} [get]
func getToExtensionById(id int) (interface{}, error) {
	ret := []ToExtension{}
	arg := ToExtension{Id: int64(id)}
	nstmt, err := db.GlobalDB.PrepareNamed(`select * from to_extension where id=:id`)
	err = nstmt.Select(&ret, arg)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	nstmt.Close()
	return ret, nil
}

// @Title getToExtensions
// @Description retrieves the to_extension information for a certain id
// @Accept  application/json
// @Success 200 {array}    ToExtension
// @Resource /api/2.0
// @Router /api/2.0/to_extension [get]
func getToExtensions() (interface{}, error) {
	ret := []ToExtension{}
	queryStr := "select * from to_extension"
	err := db.GlobalDB.Select(&ret, queryStr)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return ret, nil
}

// @Title postToExtension
// @Description enter a new to_extension
// @Accept  application/json
// @Param                 Name json     string   false "name description"
// @Param              Version json     string   false "version description"
// @Param              InfoUrl json     string   false "info_url description"
// @Param           ScriptFile json     string   false "script_file description"
// @Param             Isactive json      int64   false "isactive description"
// @Param AdditionalConfigJson json     string    true "additional_config_json description"
// @Param          Description json     string    true "description description"
// @Param ServercheckShortName json     string    true "servercheck_short_name description"
// @Param ServercheckColumnName json     string    true "servercheck_column_name description"
// @Param                 Type json      int64   false "type description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/to_extension [post]
func postToExtension(payload []byte) (interface{}, error) {
	var v ToExtension
	err := json.Unmarshal(payload, &v)
	if err != nil {
		fmt.Println(err)
	}
	sqlString := "INSERT INTO to_extension("
	sqlString += "name"
	sqlString += ",version"
	sqlString += ",info_url"
	sqlString += ",script_file"
	sqlString += ",isactive"
	sqlString += ",additional_config_json"
	sqlString += ",description"
	sqlString += ",servercheck_short_name"
	sqlString += ",servercheck_column_name"
	sqlString += ",type"
	sqlString += ") VALUES ("
	sqlString += ":name"
	sqlString += ",:version"
	sqlString += ",:info_url"
	sqlString += ",:script_file"
	sqlString += ",:isactive"
	sqlString += ",:additional_config_json"
	sqlString += ",:description"
	sqlString += ",:servercheck_short_name"
	sqlString += ",:servercheck_column_name"
	sqlString += ",:type"
	sqlString += ")"
	result, err := db.GlobalDB.NamedExec(sqlString, v)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}

// @Title putToExtension
// @Description modify an existing to_extensionentry
// @Accept  application/json
// @Param                 Name json     string   false "name description"
// @Param              Version json     string   false "version description"
// @Param              InfoUrl json     string   false "info_url description"
// @Param           ScriptFile json     string   false "script_file description"
// @Param             Isactive json      int64   false "isactive description"
// @Param AdditionalConfigJson json null.String    true "additional_config_json description"
// @Param          Description json null.String    true "description description"
// @Param ServercheckShortName json null.String    true "servercheck_short_name description"
// @Param ServercheckColumnName json null.String    true "servercheck_column_name description"
// @Param                 Type json      int64   false "type description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/to_extension [put]
func putToExtension(id int, payload []byte) (interface{}, error) {
	var v ToExtension
	err := json.Unmarshal(payload, &v)
	v.Id = int64(id) // overwrite the id in the payload
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	v.LastUpdated = time.Now()
	sqlString := "UPDATE to_extension SET "
	sqlString += "name = :name"
	sqlString += ",version = :version"
	sqlString += ",info_url = :info_url"
	sqlString += ",script_file = :script_file"
	sqlString += ",isactive = :isactive"
	sqlString += ",additional_config_json = :additional_config_json"
	sqlString += ",description = :description"
	sqlString += ",servercheck_short_name = :servercheck_short_name"
	sqlString += ",servercheck_column_name = :servercheck_column_name"
	sqlString += ",type = :type"
	sqlString += ",last_updated = :last_updated"
	sqlString += " WHERE id=:id"
	result, err := db.GlobalDB.NamedExec(sqlString, v)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}

// @Title delToExtensionById
// @Description deletes to_extension information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    ToExtension
// @Resource /api/2.0
// @Router /api/2.0/to_extension/{id} [delete]
func delToExtension(id int) (interface{}, error) {
	arg := ToExtension{Id: int64(id)}
	result, err := db.GlobalDB.NamedExec("DELETE FROM to_extension WHERE id=:id", arg)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	return result, err
}
