# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Chromedriver Updater

on:
  workflow_dispatch:
  schedule:
    # Every day at 00:00
    - cron: '0 0 * * *'

env:
  PROJECTS:

jobs:
  chromedriver-updater-tp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        id: checkout
      - name: Install Python 3.10
        uses: actions/setup-python@v2
        with: { python-version: '3.10' } # Must be quoted to include the trailing 0
      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install updater Python module and dependencies
        run: pip install .github/actions/chromedriver-updater
      - name: Run chromedriver-updater
        uses: ./.github/actions/chromedriver-updater
        env:
          GIT_AUTHOR_NAME: asf-ci-trafficcontrol
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_GITHUB_TOKEN: ${{ secrets.ASFCI_TOKEN }}
          PROJECTS: "traffic_portal/test/integration/"

  chromedriver-updater-tpv2:
    runs-on: ubuntu-latest
    needs:
      - chromedriver-updater-tp
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        id: checkout
      - name: Install Python 3.10
        uses: actions/setup-python@v2
        with: { python-version: '3.10' } # Must be quoted to include the trailing 0
      - name: Install Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install updater Python module and dependencies
        run: pip install .github/actions/chromedriver-updater
      - name: Run chromedriver-updater
        uses: ./.github/actions/chromedriver-updater
        env:
          GIT_AUTHOR_NAME: asf-ci-trafficcontrol
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_GITHUB_TOKEN: ${{ secrets.ASFCI_TOKEN }}
          PROJECTS: "experimental/traffic-portal/"
